### PR TITLE
Added CLAHE Transform

### PR DESCRIPTION
**Pull request by diegovincent**

### CODE REVIEW

**Comment by perone** [comment]
Thanks for the PR @diegovincent ! Is there any option for us to use CLAHE from `scikit-image` instead of OpenCV ? I'm afraid of adding opencv dependency only for a single function.

**Comment by diegovincent** [comment]
We (@vipermu and me) thought the same Mr. @perone. However, at the same time isn't OpenCV useful for the framework itself? We are going to add some other functions for a Cardiac Segmentation project we are currently working on. But we also agree in using `scikit-image`.

**Comment by diegovincent** [comment]
Besides, `scikit-image` is not in the project requirements either. I guess your suggestion is because `scikit-image` is lighter than OpenCV?

**Comment by perone** [comment]
Yes, scikit-image is lighter than OpenCV. Are you going to depend on OpenCV for other functions in future ? If yes then it's ok for me.

**Comment by diegovincent** [comment]
We will try to stick to scikit-image for now, if we then depend on a function that is OpenCV exclusive we will use it. We agreed with your suggestion :)

Check it out now.

**Comment by perone** [comment]
Thanks @diegovincent and @vipermu !

**Pull request merged**
